#!/usr/bin/env python3
"""Convert an exported v11.7 browser mapping JSON into a reviewed JS snippet.

This tool never edits builtin-image-mappings.js automatically. It validates that
all promoted paths are local catalog assets, then emits a candidate object for
code review / manual merge.
"""
from __future__ import annotations
import argparse, json, re
from pathlib import Path

KINDS = ('animals', 'sponsors', 'projects', 'finals')

def load_catalog(root: Path) -> set[str]:
    raw = (root / 'assets' / 'data.js').read_text(encoding='utf-8').strip()
    prefix = 'window.PORKNOVA_DATA = '
    if not raw.startswith(prefix):
        raise SystemExit('invalid assets/data.js')
    data = json.loads(raw[len(prefix):].rstrip(';'))
    paths = set()
    for kind in (*KINDS, 'maps'):
        for item in data.get(kind, []):
            if item.get('img'): paths.add(item['img'])
    for sides in data.get('actionImages', {}).values():
        paths.update(x for x in sides.values() if x)
    return paths

def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument('mapping_json', type=Path)
    ap.add_argument('--root', type=Path, default=Path(__file__).resolve().parents[1])
    ap.add_argument('--out', type=Path)
    args = ap.parse_args()
    root = args.root.resolve()
    payload = json.loads(args.mapping_json.read_text(encoding='utf-8'))
    source = payload.get('mappings', payload)
    known = load_catalog(root)
    promoted = {k:{} for k in KINDS}
    problems = []
    for kind in KINDS:
        bucket = source.get(kind, {}) if isinstance(source, dict) else {}
        if not isinstance(bucket, dict): continue
        for normalized_key, entry in bucket.items():
            if not isinstance(entry, dict): continue
            name = str(entry.get('cardName') or '').strip()
            src = str(entry.get('src') or '').strip()
            if not name:
                problems.append(f'{kind}:{normalized_key}: cardName missing')
                continue
            if src not in known or not src.startswith('assets/') or '..' in src:
                problems.append(f'{kind}:{name}: unknown/non-local asset {src!r}')
                continue
            promoted[kind][name] = {
                'src': src,
                'assetId': entry.get('assetId'),
                'confidence': 'user-verified',
                'basis': 'v11.7 exported mapping promoted after review',
            }
    if problems:
        raise SystemExit('FAIL:\n' + '\n'.join(' - '+x for x in problems))
    text = '// Candidate mappings generated by promote_image_mappings.py\n' + \
           'window.PORKNOVA_PROMOTED_IMAGE_MAPPINGS = ' + json.dumps(promoted, ensure_ascii=False, indent=2) + ';\n'
    if args.out:
        args.out.write_text(text, encoding='utf-8')
        print(f'WROTE: {args.out}')
    else:
        print(text, end='')
    print('PROMOTED:', sum(len(x) for x in promoted.values()))

if __name__ == '__main__':
    main()
